### PR TITLE
List teams in an org and list org team members

### PR DESCRIPTION
**Pull request by ateucher**
This adds two new github functions to list teams in an org, and list members in a team. My immediate use case is for joining with Grafana data to look at usage by GitHub team

### CODE REVIEW

**Comment by ateucher** [comment]
Hi @seankross - pinging you here to request a review, and to wonder how you would like to manage kyber development going forward? I know you're not in a position to work on it actively right now, so I want to respect that.

**Comment by seankross** [comment]
Hi @ateucher, I'm happy to review things for now, and this PR LGTM. We should work something out with Julie but for now I'm okay with this.

**Review by seankross — APPROVED** [review]

**Comment by ateucher** [comment]
Thanks very much @seankross, sounds good!

**Comment by jules32** [comment]
Thanks so much @seankross , definitely looking forward to chatting soon and thinking about next steps together! Thanks for supporting @ateucher and Andy for additions!

**Pull request merged**
