### PR TITLE
add water boards rmds to kyber dev

### PR DESCRIPTION
**Pull request by AHolder1**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
@AHolder1 💃🏼 What an awesome productive morning! I think you can mark this pull request as Ready for review 

Screenshot 2024-02-09 at 11 38 14 AM

@seankross We followed your recommended workflow to best of our knowledge. We think this pull request is from Anna's branch of dev into dev. She successfully created 5 agendas from these Rmds!!!

**Comment by jules32** [comment]
Woo! awesome work!

**Review by stefaniebutland — APPROVED** [review]
Thank you @AHolder1 for creating these custom Rmds for CA Water Boards Openscapes Champions Cohorts!! So great to have this first "outside" use case!
I will merge this into Main 🥳

**Comment by stefaniebutland** [comment]
And @seankross Thank you! I forgot to tag you to say I hope this doesn't cause you any issues ❤️

**Pull request merged**
