### PR TITLE
use parameterized report approach w help of @njtierney

### PR DESCRIPTION
**Pull request by stefaniebutland**
Draft PR. WIP. 
See # next steps in `create_certificate.R`

### CODE REVIEW

**Comment by jules32** [comment]
Hi @stefaniebutland , great progress! I've cleaned the code and pushed for last name only pdfs. This can be enough for this round, depending on your bandwidth. We can iterate/improve with concatenated first names for the next round. 

The PDF is not displaying the hex and it could benefit from a few more carraige returns potentially `<br>`; not sure how much this is worth tinkering now since PDFs can be tricky; so tinker a bit but also could be fine as is; ok if no hex this first round. 

Thank you!!!

image

**Comment by stefaniebutland** [comment]
@jules32 Thanks so much for the code cleanup and pdf output! 
I added participant_name (last name only) to text of certificate and that will be the version used for now. I tried adding first name too (printed correct last name plus *all* first names in every certificate) and realized I need to learn a little more before spending more time

**Comment by stefaniebutland** [comment]
Status: Need to merge main into the https://github.com/Openscapes/kyber/tree/cert-completion branch, update this PR if needed, test and merge into main

**Comment by ateucher** [comment]
@stefaniebutland I think this is ready to merge. I extracted the non-function code into a vignette and created documentation for the `render_certificate()` function. We could do a bit more in terms of checking inputs and add some tests, but if you're keen to get this merged now it is working, and we can address the extras later?

**Pull request merged**
